name: CI/CD Develop Workflow

on:
  push:
    branches:
      - develop
  workflow_call:
    inputs:
      container-registry-name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      VULTR_API_KEY:
        required: true

jobs:  

  build-container-image:
    name: Build Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: List Container Registry
        shell: bash
        run: |
          apt-get install -y jq
          curl -s \
            -H "Authorization: Bearer ${{ secrets.VULTR_API_TOKEN }}" \
            "https://api.vultr.com/v2/registries" > response.json

          VULTR_REGISTRY_HOST=$(jq -r '.registries[] | select(.name == "${{ inputs.container-registry-name }}") | "https://" + .urn' response.json)
          echo "VULTR_REGISTRY_HOST=${VULTR_REGISTRY_HOST}" >> $GITHUB_ENV

          VULTR_REGISTRY_USERNAME=$(jq -r '.registries[0].root_user.username' response.json)
          echo "VULTR_REGISTRY_USERNAME=${VULTR_REGISTRY_USERNAME}" >> $GITHUB_ENV

          VULTR_REGISTRY_PASSWORD=$(jq -r '.registries[0].root_user.password' response.json)
          echo "VULTR_REGISTRY_PASSWORD=${VULTR_REGISTRY_PASSWORD}" >> $GITHUB_ENV

          echo "VULTR_REGISTRY_HOST: $VULTR_REGISTRY_HOST"
          echo "VULTR_REGISTRY_USERNAME: $VULTR_REGISTRY_USERNAME"
          echo "VULTR_REGISTRY_PASSWORD: $VULTR_REGISTRY_PASSWORD"

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Vultr Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.VULTR_REGISTRY_HOST }}
          username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
          password: ${{ secrets.VULTR_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.container-registry-name }}:${{ github.sha }}

      - name: Logout from Docker Registry
        run: docker logout ${{ secrets.VULTR_REGISTRY_HOST }}
