name: CI/CD Infra Reusable Workflow - Deploy

on:
  workflow_call:
    inputs:
      bucket-tf-backend-name:
        required: true
        type: string
      key-tf-backend-name:
        required: true
        type: string
    secrets:
      VULTR_API_KEY:
        required: true
      VULTR_SSH_PUBLIC_KEY:
        required: false
        description: "Optional SSH public key for Vultr instances"
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-execute:
    name: 🦾 Terraform execute deploy infra
    runs-on: ubuntu-latest
    env:
      TF_LOG: TRACE
      TF_VAR_VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
      TF_VAR_VULTR_SSH_PUBLIC_KEY: ${{ secrets.VULTR_SSH_PUBLIC_KEY }}      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="./environments/terraform.tfvars" -out=tfplan    

      - name: Terraform Apply
        run: terraform apply "tfplan" -auto-approve
